version: "3.9"

services:
  database:
    build: ./database                  
    container_name: my-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build: ./Backend                   
    container_name: backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-net

  httpd:
    build: ./httpd                    
    container_name: http-server
    depends_on:
      - backend
    ports:
      - "80:80"                        
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db-data:
