all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    prod:
      hosts:
        production:
          ansible_host: "{{ lookup('env', 'SERVER_HOST') | default('yannick.tiendjeungaleu.takima.cloud') }}"
