all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
children:
   prod:
     hosts:
       yannick.tiendjeungaleu.takima.cloud:
