#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      - python3-venv
    state: latest
    update_cache: yes
  become: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true

- name: Add Docker apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: yes
  become: true

- name: Install Docker CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  notify: Restart docker
  become: true

- name: Ensure docker service enabled & running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
